In [1]:
import tensorflow as tf
import csv,cv2, numpy as np
import pandas as pd

In [2]:
'''
Data Extraction Phase
This block is reading the files and placing into numpy arrays that
will be preprocessed and finally fed into the deep neural network
'''


uploadFromPreviousRun = np.load('../assignment_3/data_downloaded/data/Behavioral_Cloning_1_8036.npz')
X_train = uploadFromPreviousRun['X_train']
y_train = uploadFromPreviousRun['y_train']
print(X_train.shape,y_train.shape)


## Data Appending
# uploadFromPreviousRun1 = np.load('../assignment_3/data_downloaded/data/Behavioral_Cloning_1_7000.npz')
# uploadFromPreviousRun2 = np.load('../assignment_3/data_downloaded/data/Behavioral_Cloning_7000_8036.npz')

# X_train1 = uploadFromPreviousRun1['X_train']
# y_train1 = uploadFromPreviousRun1['y_train']

# X_train2 = uploadFromPreviousRun2['X_train']
# y_train2 = uploadFromPreviousRun2['y_train']

# print(X_train1.shape,y_train1.shape)
# print(X_train2.shape,y_train2.shape)

# # y_train1 = uploadFromPreviousRun1['y_train']
# # y_train2 = uploadFromPreviousRun2['y_train']

# X_train1 = np.append(X_train1,X_train2,axis=0)
# y_train1 = np.append(y_train1,y_train2,axis=0)
# print(X_train1.shape,y_train1.shape)

# np.savez_compressed('../assignment_3/data_downloaded/data/Behavioral_Cloning_1_8036',X_train=X_train1,y_train=y_train1)


## Reading real file
# # relativeLocation = '../assignment_3/data/lane1/'
# relativeLocation = '../assignment_3/data_downloaded/data/'
# df = pd.read_csv(relativeLocation + 'driving_log.csv')

# ## Initialization
# # Initialization of numpy array with the first image is already done
# counterStart = 7000
# counterNumImagesMax = 1036
# X_train = np.empty((0,160,320,3),np.uint8)
# y_train = np.array(df['steering'])[counterStart:counterStart+counterNumImagesMax]

# counterNumImages = 0
# ## Extraction loop
# for imageName in df['center'][counterStart:counterStart + counterNumImagesMax]:
#     image_path = relativeLocation + '/IMG/' + imageName.split('/')[-1]
#     new_image = cv2.imread(image_path)
    
#     new_image = cv2.imread(image_path).reshape((1,160,320,3))
#     X_train = np.append(X_train,new_image,axis=0)
    
#     counterNumImages = counterNumImages+1
#     print(counterNumImages)
#     if counterNumImages == counterNumImagesMax:
#         break

        
# X_train_Flipped = np.empty((0,160,320,3),np.uint8)
# # Add mirror_image into the data
# for image in X_train:
#     flippedImage = np.fliplr(image).copy() #Comment 1 : this copy looks important
#      #fliplr just flips something that is not data
#     X_train_Flipped = np.append(X_train_Flipped,new_image,axis=0)
#     counterNumImages = counterNumImages + 1
#     print(counterNumImages)

    
# X_train = np.append(X_train,X_train_Flipped,axis=0)
# y_train = np.append(y_train,-y_train)

# print(X_train.shape,y_train.shape)

# np.savez_compressed('../assignment_3/data_downloaded/data/Behavioral_Cloning_7000_8036',X_train=X_train,y_train=y_train)

(16072, 160, 320, 3) (16072,)


In [3]:
'''
Data PreAnalysis Phase
Look at the max and min values of the Steering, Throttle, Break, Speed
'''
print('Each image is of shape : ',X_train[1].shape)

Each image is of shape :  (160, 320, 3)


In [4]:
'''
Keral library imports
'''
from keras.models import Sequential
from keras.layers import Flatten, Dense, Activation, Lambda, Cropping2D
from keras.layers import Conv2D, MaxPooling2D, Dropout

Using TensorFlow backend.


model = Sequential

In [14]:
'''
Keras network description
'''

# Graph Description
model = Sequential()
model.add(Lambda(lambda x: x/255.0 - 0.5, input_shape=(160,320,3))) #Normalization layer
model.add(Cropping2D(cropping=((70,25),(0,0))))

# Layer : Conv 1
model.add(Conv2D(24, activation="relu", kernel_size=(5, 5), strides=(2, 2)))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))

# Layer : Conv 2
model.add(Conv2D(36, activation="relu", kernel_size=(5, 5), strides=(2, 2)))
# model.add(Conv2D(32,kernel_size=(5, 5),activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))

# Layer : Conv 3
model.add(Conv2D(48, activation="relu", kernel_size=(5, 5), strides=(2, 2)))

# model.add(Conv2D(32,kernel_size=(3, 3),activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))

# Layer : Conv 4
model.add(Conv2D(64, activation="relu", kernel_size=(3, 3)))

# model.add(Conv2D(32,kernel_size=(3, 3),activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))
# model.add(Flatten())

# Layer : Conv 5
model.add(Conv2D(64, activation="relu", kernel_size=(3, 3)))
model.add(Flatten())

# Layer : Dense 6
model.add(Dense(100))
# model.add(Activation('relu'))
# model.add(Dropout(0.25))


# Layer : Dense 6
model.add(Dense(50))
# model.add(Activation('relu'))
# model.add(Dropout(0.25))


# Layer : Dense 7
model.add(Dense(10))
# model.add(Activation('relu'))
# model.add(Dropout(0.25))


# Layer : Dense 7 Output
model.add(Dense(1))


# Network optimization choices set to mse and adam optimizer
model.compile(loss='mse',optimizer='adam')
          
# Network training happening here
model.fit(X_train,y_train, validation_split=0.2, shuffle=True, 
          epochs = 11, batch_size=256)
model.save('model_11A.h5')

TypeError: ('Keyword argument not understood:', 'Dropout')

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,5,7,8,27,22,55])

In [8]:
b = a[a>4]

In [7]:
print(b)

[[[[[[[ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      ...
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]]

     [[ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      ...
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]]

     [[ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      ...
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]]

     ...

     [[ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      ...
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]]

     [[ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      ...
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]
      [ 0  0  0 ...  0  0  0]]

     [[ 0  0  0 ...  0  0  0]
